### ISSUE TITLE
Too bad it does not work

### ISSUE THREAD

**Issue by XenocodeRCE** [TobitoFatitoNulled/Venturi77CallHijacker#1]
Hello

**Describe the bug**
The CallHijacker always return 

```
Detected: Unknown
Unknown Obfuscator!
```
or
```
Failed Injecting KoiVM
```
against standard KoiVM files

**To Reproduce**
1. Fork https://github.com/yck1509/ConfuserEx
2. Fork https://github.com/yck1509/KoiVM
3. Merge the two repo & build
4. Mark any file method to be virtualized
5. Add the Crproj rules
6. Protect marked file
7. Run Venturi77Hijacker.exe
8. Enter `1`
9. Drag and drop the protected file into the console
10. Click enter
11. Enter `1`

Console should prompt : 

```
Detected: Unknown
Unknown Obfuscator!
```

**Expected behavior**
I think if i'm not wrong the dll shall be injected or at least KoiVM should be found when scanning for the assembly

**Screenshots**
I recorded myself https://www.sendspace.com/file/j76crp

**Desktop (please complete the following information):**
 - OS:  Windows 10 x64
 - TestApp compiled target FW 4.0

**Additional context**
- My fork of KoiVM merged with ConfuserEx (non-touched, just a simple fork with no added code) [here](https://github.com/XenocodeRCE/KoiVM)
- TestApp source is [here](https://github.com/XenocodeRCE/KoiVM/blob/master/Confuser.UnitTest/Program.cs#L18)

Here is my crproj file content, ignore paths for your tests

```xml
<project outputDir="C:\Users\xenocode\source\repos\KoiVM\Debug\bin\Confused" baseDir="C:\Users\xenocode\source\repos\KoiVM\Debug\bin" xmlns="http://confuser.codeplex.com">
  <module path="Confuser.UnitTest.exe">
    <rule pattern="true" inherit="false">
      <protection id="constants" />
      <protection id="koi" />
    </rule>
  </module>
  <plugin>C:\Users\xenocode\source\repos\KoiVM\Debug\bin\KoiVM.Confuser.exe</plugin>
</project>
```

**Comment by TobitoFatitoNulled** [comment]
On it, will push the update once home.

**Comment by TobitoFatitoNulled** [comment]
For now try drag and dropping the .dll

**Comment by TobitoFatitoNulled** [comment]
Check latest push, i replicated everything and made it work, you just have to remove _Inj from the .dll that gets saved (can't replace it at runtime for some reason)

**Comment by XenocodeRCE** [comment]
Sorry, can you compile and fix current release ? since current release contains the buggy/non working hijacker

**Comment by TobitoFatitoNulled** [comment]
The compiled releases contain the working version? Did you try it and it didnt work or something?

**Comment by XenocodeRCE** [comment]
Hello,

sorry I did not see you took time to update the release files.

so I tested on 2 test apps, one with generic types and one without, it works on the later, however for the former generic methods inside non generic types get merged somehow, after using KoiVM the type lacks its generic methods but the code still get executed. 
 
it's a nice tool to patch virtual call in the VM nonetheless

I'll try to see what can I do with KoiVM now regarding this, also I wonder why #koi is not hashed or even ecoded in the version he released publicly, on the one he sent me the handlers get mutated and #koi is protected a little bit...

I'll close my post now, thank you for the update
