### ISSUE TITLE
[Suggestion] Convert this app to Winforms

### ISSUE THREAD

**Issue by ewwink** [TobitoFatitoNulled/Venturi77CallHijacker#3]
Nice project, If you have a plan for long term updates I suggest to make this program as Winforms with config builder and I think `JSON` config is not really needed, maybe replace it with simple config like: 

```
SearchBy: MethodName
SearchFor: method1
ReplaceResultWith: false
Parameter: 0

SearchBy: MethodName
SearchFor: method2
ReplaceResultWith: Serial is valid
Parameter: 0
```

**Comment by TobitoFatitoNulled** [comment]
JSON just makes everything easier, i might change to simplejson but i don't think that i'm leaving json. If you can fork this and update it yourself making it have as many features i'd definitely merge :)
As of winforms, i really suck at it i doubt i'd make a decent UI.

**Comment by ewwink** [comment]
JSON is easier for writing with program but not if I edit the file using text editor, sometime I miss to type the `{},"`  but its not a big problem. 

Simplejson would be good alternative so we didn't need to copy 2 .dll to the target directory. I will close this for now and thanks.
